### ISSUE TITLE
Outstanding issues with the pr2-kinect2-packages

### ISSUE THREAD

**Issue by TheDash** [pr2-debs/pr2-kinect2-packages#6]
@archielee from forward on, issues are to be logged publicly and bug reports/features to be added are to be commented on and documented here.

- [x] Add to README that after installation, user must add their computer to the NUC's /etc/hosts file and add the NUC to their own hosts file

- [x] make release candidate and tag stable for release

- [x] Linking transforms from kinect2_bridge to PR2 model (see pr2-kinect2-config issues)

- [x] time synchronization issues with pr2-head

**Comment by archielee** [comment]
Current to-do:

- [ ] Add to README that after installation, user must add their computer to the NUC's /etc/hosts file and add the NUC to their own hosts file

**Comment by TheDash** [comment]
Please make a new issue and log it there. this issue is meant to be a library/index for all existing issues until we can make a release candidate

**Comment by archielee** [comment]
Making new issue for the fixed frame issue where base_link isn't recognized
